### ISSUE TITLE
Fatal error:java.lang.NoSuchMethodError: OptionDescriptor.create

### ISSUE THREAD

**Issue by mtalijanac** [ByerN/libgdx-graalvm-example#1]
I have tried to follow compilation steps described in readme.md but I always end up with GraalVM error. I am able to build fat desktop.jar and run it successfully with run_with_agent.bat. I don't see graalvm classes within generated config files. My environment is:

- windows 10
- graalvm-ce-java11-20.1.0  or graalvm-ce-java11-21.3.0
- gradle 6.7.1

The error happens while runing build_native.bat:

$ native-image.cmd -H:+ReportExceptionStackTraces --report-unsupported-elements-at-runtime --initialize-at-run-time=org.lwjgl --no-fallback --allow-incomplete-classpath -H:ReflectionConfigurationFiles=config/reflect-config.json -H:JNIConfigurationFiles=config/jni-config.json -H:DynamicProxyConfigurationFiles=config/proxy-config.json -H:SerializationConfigurationFiles=config/serialization-config.json -H:ResourceConfigurationFiles=config/resource-config.json -Dorg.lwjgl.librarypath=. -ja

Fatal error:java.lang.NoSuchMethodError: 'org.graalvm.compiler.options.OptionDescriptor org.graalvm.compiler.options.OptionDescriptor.create(java.lang.String, org.graalvm.compiler.options.OptionType, java.lang.Class, java.lang.String, java.lang.Class, java.lang.String, org.graalvm.compiler.options.OptionKey, boolean)'
        at org.graalvm.compiler.loop.LoopPolicies_OptionDescriptors.get(LoopPolicies_OptionDescriptors.java:17)
        at org.graalvm.compiler.loop.LoopPolicies_OptionDescriptors$1.next(LoopPolicies_OptionDescriptors.java:43)
        at org.graalvm.compiler.loop.LoopPolicies_OptionDescriptors$1.next(LoopPolicies_OptionDescriptors.java:34)
        at com.oracle.svm.hosted.option.HostedOptionParser.collectOptions(HostedOptionParser.java:76)
        at com.oracle.svm.hosted.option.HostedOptionParser.<init>(HostedOptionParser.java:60)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:277)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:569)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:599)
     [total]:   4,388.08 ms,  0.96 GB
Error: Image build request failed with exit status 1

**Comment by ByerN** [comment]
I was testing on: graalvm-ce-java11-21.0.0.2
Could you change the version to one you are using in https://github.com/ByerN/libgdx-graalvm-example/blob/master/build.gradle
and let me know if it solved the problem? If so I will add a solution to README.

**Comment by mtalijanac** [comment]
I have managed to build exe file using:
 - graalvm-ce-java11-21.0.0
 - graalvm-ce-java11-21.0.0.2
 - graalvm-ce-java8-21.0.0
 - graalvm-ce-java8-21.0.0.2

But the exe won't run as it is missing dlls in path. So I have copied following x64 dlls from fat-jar to a root of graalvm-env folder:
 - gdx-box2d64.dll
 - gdx-freetype64.dll
 - gdx64.dll
 - glfw.dll
 - jamepad64.dll
 - jemalloc.dll
 - lwjgl.dll
 - lwjgl_opengl.dll
 - OpenAL.dll

Now with those dlls in place application starts, some loging happens, basic window is drawn, but than it closes immediately without any error being thrown. I presume opengl initialization goes wrong but I do not known anything about OpenGL, GraalVM or libgdx. It's strange as app works perfectly fine when run on GraalVM java. Aynway I have uploaded [binary files](https://drive.google.com/file/d/1jE2lfGzt-yEFsonW32UZcDm-QIB-BZRq/view?usp=sharing), if you could take a look.

The exact versions of tools used for this build were:
 - windows 10 Pro 64-bit, 17134
 - Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30138 for x64
 - OpenJDK Runtime Environment GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06)
 - Gradle 6.7.1
 - Apache Maven 3.8.4

I have built libgdx-contribs-postprocessing dependency myself as it is not present on maven central.

**Comment by mtalijanac** [comment]
In order to exclude driver related problems I have tried to run this binary on multiple computers using diferent gpus. But it behaves the same:
 - AMD FX8320e + Nvidia GTX 1080
 - i7 8700 + Intel UHD 630
 - i7 8700 + Nvidia Quadro P1000
